#!/sbin/busybox sh

export BOOTREC_CACHE_NODE="/dev/block/mtdblock3 b 31 3"
export BOOTREC_CACHE="/dev/block/mtdblock3"
export BOOTREC_EVENT_NODE="/dev/input/event1 c 13 65"
export BOOTREC_EVENT="/dev/input/event1"
